name: Pyre Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pyre-check:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
      - name: Checkout Torchrec
        uses: actions/checkout@v3
      - name: Install dependencies
        run: >
          conda install --yes -c pytorch-nightly "pytorch-nightly"::pytorch[build="*cpu*"] &&
          sed -i 's/fbgemm-gpu-nightly/fbgemm-gpu-nightly-cpu/g' requirements.txt &&
          pip install -r requirements.txt &&
          pip install pyre-check-nightly==$(cat .pyre_configuration | grep version | awk '{print $2}' | sed 's/\"//g')
      - name: Pyre check
        run: pyre check
